# Paper Parameters

## General
F_SIZE = 128

## Signal Processing
ALPHA = 0.85
N_CEPSTRUM_COEFFS = 18
N_FEATURES = 20
SR = 16000
N_FRAMES = 15
N_SAMPLES_IN_FRAME = 160
M = 16
MU = 255

## Training
BATCH_SIZE = 64
EPOCHS = 120
ALPHA0 = 0.001
DELTA = 5e5

## Frame Network
CONVOLUTION_KERNEL_SIZE = 3
SECOND_FC_LAYER_SIZE = 128

## Sample Network
FIRST_GRU_LAYER_SIZE = 384
SECOND_GRU_LAYER_SIZE = 16
DUAL_FC_LAYER_SIZE = 256

# My Implementation Parameters

## Signal Processing
N_FILTERS = 24
HOP_LENGTH = 512

## Frame Network
FIRST_CONV_LAYER_FILTERS_SIZE = 128
FIRST_CONV_LAYER_ACTIVATION_FUNCTION = "tanh"
SECOND_CONV_LAYER_FILTERS_SIZE = 128
SECOND_CONV_LAYER_ACTIVATION_FUNCTION = "tanh"
FIRST_FC_LAYER_SIZE = 128
FIRST_FC_LAYER_ACTIVATION_FUNCTION = "tanh"
SECOND_FC_LAYER_ACTIVATION_FUNCTION = "tanh"

## Sample Network
GUMBEL_SOFTMAX_TEMPERATURE = 0.5